[build]
target = ".cargo/x86_64-lzh_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
rustflags = [
    "-C", "link-arg=--image-base=0x200000",
    "-C", "target-feature=+soft-float,-sse,-mmx",
    "-C", "relocation-model=static",
]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true